pipeline {
    agent any
    tools {
        nodejs 'node-install' 
    }
    environment {
        DOCKER_IMAGE = "linab1234/crisiview-front:v1"
        DOCKER_HUB_CREDS = 'docker-hub-credentials'
    }
    stages {
        stage('Checkout') {
            steps { 
                checkout scm 
            }
        }
        
        stage('Build & Install') {
            steps {
                dir('frontend_crisisview-main') { 
                    sh 'npm install'
                }
            }
        }

        stage('Static Analysis (Sonar)') {
            steps {
                dir('frontend_crisisview-main') {
                    withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TOKEN')]) {
                        sh "npx sonar-scanner \
                        -Dsonar.projectKey=crisiview-frontend \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=http://host.docker.internal:9000 \
                        -Dsonar.login=${SONAR_TOKEN}"
                    }
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Artifact') {
            steps {
                dir('frontend_crisisview-main') {
                    sh 'npm run build'
                }
            }
        }

        stage('Docker Packaging') {
            steps {
                echo "Build de l'image ${DOCKER_IMAGE} terminée avec succès."
            }
        }
    }
}