pipeline {
    agent any
    tools {
        nodejs 'node-install' 
    }
    environment {
        DOCKER_IMAGE = "linab1234/crisiview-front:v1"
        DOCKER_HUB_CREDS = 'docker-hub-credentials'
    }
    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Build & Install') {
            steps {
                dir('frontend_crisisview-main') { 
                    sh 'npm install'
                }
            }
        }
        stage('Build Artifact') {
            steps {
                dir('frontend_crisisview-main') {
                    sh 'npm run build'
                }
            }
        }
        stage('Docker Packaging') {
            steps {
                echo "Build de l'image crisiview-front..."
            }
        }
    }
}