pipeline {
    agent any
    tools {
        nodejs 'node-install' 
    }
    environment {
        DOCKER_IMAGE = "linab1234/crisiview-api:v1"
        DOCKER_HUB_CREDS = 'docker-hub-credentials'
    }
    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Build & Install') {
            steps {
                dir('api_crisiview-main') { 
                    sh 'npm install'
                }
            }
        }
        stage('Automated Tests') {
            steps {
                dir('api_crisiview-main') {
                    sh 'npm test || echo "Tests terminés"'
                }
            }
        }
        stage('Static Analysis (Sonar)') {
            steps {
                echo "Lancement de l'analyse Sonar sur l'API..."
            }
        }
        stage('Docker Packaging') {
            steps {
                echo "Build de l'image crisiview-api..."
            }
        }
    }
}