pipeline {
    agent any
    tools {
        nodejs 'node-install' 
    }
    environment {
        DOCKER_IMAGE = "linab1234/crisiview-api:v1"
        DOCKER_HUB_CREDS = 'docker-hub-credentials'
    }
    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Build & Install') {
            steps {
                dir('api_crisiview-main') { 
                    sh 'npm install'
                }
            }
        }
        stage('Automated Tests') {
            steps {
                dir('api_crisiview-main') {
                    sh 'npm test || echo "Tests terminés"'
                }
            }
        }
        stage('Static Analysis (Sonar)') {
    steps {
        dir('api_crisiview-main') {
            withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TOKEN')]) {
                sh "npx sonar-scanner \
                -Dsonar.projectKey=crisiview-api \
                -Dsonar.sources=. \
                -Dsonar.host.url=http://host.docker.internal:9000 \
                -Dsonar.login=${SONAR_TOKEN}"
            }
        waitForQualityGate abortPipeline: true
        }
    }
        }
        stage('Docker Packaging') {
            steps {
                echo "Build de l'image crisiview-api..."
            }
        }
    }
}